### ISSUE TITLE
Cannot find module 'has-flag'

### ISSUE THREAD

**Issue by xmlking** [sis0k0/nativescript-webpack-sass#3]
Getting follow error while starting this example app:
Node : 8.0.0, tried both yarn and npm5.0.2 but same error... 

```
npm run ns-bundle --android --start-app 

> @ ns-bundle /dev/nativescript-webpack-sass
> ns-bundle

Removing platform android...
Adding platform android@3.0.0...
Running webpack for android...
module.js:487
    throw err;
    ^

Error: Cannot find module 'has-flag'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/dev/nativescript-webpack-sass/node_modules/webpack/node_modules/supports-color/index.js:2:15)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
child process exited with code 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ ns-bundle: `ns-bundle`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ ns-bundle script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xyz/.npm/_logs/2017-06-04T05_27_27_194Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

package.json
```json
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.webpackSass",
    "tns-android": {
      "version": "3.0.0"
    }
  },
  "dependencies": {
    "@angular/animations": "4.1.3",
    "@angular/common": "4.1.3",
    "@angular/compiler": "4.1.3",
    "@angular/core": "4.1.3",
    "@angular/forms": "4.1.3",
    "@angular/http": "4.1.3",
    "@angular/platform-browser": "4.1.3",
    "@angular/router": "4.1.3",
    "nativescript-angular": "~3.0.0",
    "nativescript-theme-core": "~1.0.2",
    "reflect-metadata": "~0.1.8",
    "rxjs": "^5.4.0",
    "tns-core-modules": "~3.0.1",
    "zone.js": "~0.8.11"
  },
  "devDependencies": {
    "@angular/compiler-cli": "4.1.3",
    "@ngtools/webpack": "1.4.0",
    "babel-traverse": "6.24.1",
    "babel-types": "6.24.1",
    "babylon": "6.17.2",
    "copy-webpack-plugin": "~4.0.1",
    "extract-text-webpack-plugin": "~2.1.0",
    "lazy": "1.0.11",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-dev-sass": "^1.1.0",
    "nativescript-dev-typescript": "^0.4.5",
    "nativescript-dev-webpack": "^0.6.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.0.2",
    "sass-loader": "^6.0.5",
    "typescript": "^2.3.4",
    "webpack": "~2.6.1",
    "webpack-sources": "~1.0.1"
  },
  "scripts": {
    "ns-bundle": "ns-bundle",
    "start-android-bundle": "npm run ns-bundle --android --start-app",
    "start-ios-bundle": "npm run ns-bundle --ios --start-app",
    "build-android-bundle": "npm run ns-bundle --android --build-app",
    "build-ios-bundle": "npm run ns-bundle --ios --build-app",
    "publish-ios-bundle": "npm run ns-bundle --ios --publish-app"
  }
}

```

**Comment by sis0k0** [comment]
Can't reproduce the error. If you still have it, please reopen and send the `yarn.lock` and `package-lock.json`.

**Comment by vste23** [comment]
Having the same error. Lock file is here - https://drive.google.com/open?id=0B7Pwf-K9zveLV3IwNjBuUS1PUTQ

**Comment by niftylettuce** [comment]
Same error here.

**Comment by niftylettuce** [comment]
```
Error: Cannot find module 'has-flag'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/niftylettuce/Public/koa-better-error-handler/node_modules/mocha/node_modules/supports-color/index.js:2:15)
    at Module._compile (module.js:569:30)
    at Module.replacementCompile (/Users/niftylettuce/Public/koa-better-error-handler/node_modules/append-transform/index.js:58:13)
    at Module._extensions..js (module.js:580:10)
    at require.extensions.(anonymous function) (/Users/niftylettuce/Public/koa-better-error-handler/node_modules/babel-register/lib/node.js:152:7)
    at Object.<anonymous> (/Users/niftylettuce/Public/koa-better-error-handler/node_modules/append-transform/index.js:62:4)
```

**Comment by jasonhulbert** [comment]
Removing `node_modules` and `package-lock.json` then reinstalling resolved this for me

**Comment by MikhaelGerbet** [comment]
@jasonhulbert you are saved my week !

**Comment by MikhaelGerbet** [comment]
i have (by error) commited my package-lock.json !

**Comment by TrueWill** [comment]
@MikhaelGerbet package-lock.json is intended to be committed into source repositories.
